module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-prettier/recommended'],

  plugins: [
    'stylelint-use-nesting',
    'stylelint-no-nested-media',
    'stylelint-no-unsupported-browser-features',
    'stylelint-high-performance-animation',
    'stylelint-order',
    'stylelint-color-format',
    'stylelint-a11y',
  ],

  rules: {
    // Possible errors(https://stylelint.io/user-guide/rules/list#possible-errors) by stylelint-config-recommended(included in stylelint-config-standard): https://github.com/stylelint/stylelint-config-recommended/blob/master/index.js;

    // Stylistic issues(https://stylelint.io/user-guide/rules/list#stylistic-issues) by stylelint-config-recommended: https://github.com/stylelint/stylelint-config-standard/blob/master/index.js but plenty of this nullified by stylelint-prettier and handled itself: https://github.com/prettier/stylelint-config-prettier/blob/master/src/index.js - next rules fix it
    'at-rule-empty-line-before': [
      'always',
      {
        except: ['blockless-after-same-name-blockless', 'first-nested'],
        ignore: ['after-comment'],
      },
    ],

    /*
     * https://stylelint.io/user-guide/rules/list/#limit-language-features
     * kebab-case
     */
    'keyframes-name-pattern': /^[a-z]+([a-z0-9-]+[a-z0-9]+)?$/,
    'custom-property-pattern': /^[a-z]+([a-z0-9-]+[a-z0-9]+)?$/,
    'custom-media-pattern': /^[a-z]+([a-z0-9-]+[a-z0-9]+)?$/,

    // CSS-in-JS
    'function-name-case': [
      'lower',
      { ignoreFunctions: [/.*(hexToRgb|pxToRem).*/] },
    ],
    'value-keyword-case': [
      'lower',
      {
        ignoreKeywords: [
          /.*(htmlFontSize|hoverOpacity|selectedOpacity|disabledBackground|disabledOpacity|focusOpacity|activatedOpacity).*/,
        ],
      },
    ],
    'no-empty-source': null,

    'value-no-vendor-prefix': true,
    'property-no-vendor-prefix': true,
    'selector-no-vendor-prefix': true,
    'media-feature-name-no-vendor-prefix': true,
    'at-rule-no-vendor-prefix': true,

    'alpha-value-notation': 'number',
    'hue-degree-notation': 'angle',
    'color-function-notation': 'modern',
    'color-named': 'always-where-possible',
    'color-no-hex': true,
    'font-weight-notation': 'numeric',
    'function-url-no-scheme-relative': true,
    'number-max-precision': 2,

    // TODO: we can make it more strict for individual props, see https://stylelint.io/user-guide/rules/list/unit-allowed-list/#optional-secondary-options and https://stylelint.io/user-guide/rules/list/declaration-property-unit-allowed-list/ and https://stylelint.io/user-guide/rules/list/declaration-property-value-allowed-list/
    'unit-allowed-list': [
      '%',
      'em',
      'rem',
      'vh',
      'vw',
      'vmin',
      'vmax',
      'px',
      'deg',
      's',
      'ms',
      'dpi',
    ],

    'shorthand-property-no-redundant-values': true,
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-no-important': true,
    'selector-combinator-disallowed-list': [' '],
    'selector-max-id': 0,
    'selector-max-type': 0,
    'selector-pseudo-element-colon-notation': 'single',

    // FIXME: for appending it should be discussed
    'media-feature-name-allowed-list': [
      'min-width',
      'color',
      'prefers-reduced-motion',
    ],
    'media-feature-name-value-allowed-list': {
      'min-width': ['0', '0px', '600px', '768px', '992px', '1200px'],
    },
    'no-unknown-animations': true,

    /*
     * TODO: not sure about this
     * 'at-rule-allowed-list': [],
     * also see https://stylelint.io/user-guide/rules/list/at-rule-property-required-list/
     */

    // https://github.com/stylelint/awesome-stylelint#plugins
    'csstools/use-nesting': 'always',
    'pitcher/no-nested-media': true,
    'plugin/no-unsupported-browser-features': [
      true,
      {
        severity: 'warning',
        ignorePartialSupport: true,
      },
    ],
    'plugin/no-low-performance-animation-properties': [
      true,
      { ignore: 'paint-properties' },
    ],
    'color-format/format': {
      format: 'rgb',
    },
    'a11y/content-property-no-static-value': true,
    'a11y/media-prefers-reduced-motion': true,
    'a11y/no-display-none': true,
    'a11y/no-obsolete-attribute': true,
    'a11y/no-obsolete-element': true,
    'a11y/no-outline-none': true,
    'a11y/no-text-align-justify': true,
    'a11y/selector-pseudo-class-focus': true,

    // https://github.com/fullstack-development/react-redux-starter-kit/blob/master/.stylelintrc
    'order/order': [
      'dollar-variables',
      'at-rules',
      'declarations',
      {
        type: 'at-rule',
        name: 'keyframes',
      },
      {
        type: 'at-rule',
        name: 'media',
      },
      {
        type: 'at-rule',
        name: 'include',
      },
      'rules',
    ],
    'order/properties-order': [
      [
        'lost-utility',
        'lost-flex-container',
        'lost-center',
        'lost-align',
        'lost-column',
        'lost-row',
        'lost-waffle',
        'lost-offset',
        'lost-move',
        'lost-masonry-wrap',
        'lost-masonry-column',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'display',
        'visibility',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'flex-direction',
        'flex-flow',
        'flex-wrap',
        'align-content',
        'align-items',
        'align-self',
        'justify-content',
        'order',
        'float',
        'clear',
        'overflow',
        'overflow-x',
        'overflow-y',
        'overflow-scrolling',
        'clip',
        'box-sizing',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'min-width',
        'min-height',
        'max-width',
        'max-height',
        'width',
        'height',
        'outline',
        'outline-width',
        'outline-style',
        'outline-color',
        'outline-offset',
        'border',
        'border-spacing',
        'border-collapse',
        'border-width',
        'border-style',
        'border-color',
        'border-top',
        'border-top-width',
        'border-top-style',
        'border-top-color',
        'border-right',
        'border-right-width',
        'border-right-style',
        'border-right-color',
        'border-bottom',
        'border-bottom-width',
        'border-bottom-style',
        'border-bottom-color',
        'border-left',
        'border-left-width',
        'border-left-style',
        'border-left-color',
        'border-radius',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-right-radius',
        'border-bottom-left-radius',
        'border-image',
        'border-image-source',
        'border-image-slice',
        'border-image-width',
        'border-image-outset',
        'border-image-repeat',
        'border-top-image',
        'border-right-image',
        'border-bottom-image',
        'border-left-image',
        'border-corner-image',
        'border-top-left-image',
        'border-top-right-image',
        'border-bottom-right-image',
        'border-bottom-left-image',
        'background',
        'background-color',
        'background-image',
        'background-attachment',
        'background-position',
        'background-position-x',
        'background-position-y',
        'background-clip',
        'background-origin',
        'background-size',
        'background-repeat',
        'box-decoration-break',
        'box-shadow',
        'color',
        'table-layout',
        'caption-side',
        'empty-cells',
        'list-style',
        'list-style-position',
        'list-style-type',
        'list-style-image',
        'quotes',
        'content',
        'counter-increment',
        'counter-reset',
        '-ms-writing-mode',
        'vertical-align',
        'text-align',
        'text-align-last',
        'text-decoration',
        'text-emphasis',
        'text-emphasis-position',
        'text-emphasis-style',
        'text-emphasis-color',
        'text-indent',
        'text-justify',
        'text-outline',
        'text-transform',
        'text-wrap',
        'text-overflow',
        'text-overflow-ellipsis',
        'text-overflow-mode',
        'text-shadow',
        'white-space',
        'word-spacing',
        'word-wrap',
        'word-break',
        'overflow-wrap',
        'tab-size',
        'hyphens',
        'letter-spacing',
        'font',
        'font-weight',
        'font-style',
        'font-variant',
        'font-size-adjust',
        'font-stretch',
        'font-size',
        'font-family',
        'src',
        'line-height',
        'interpolation-mode',
        'opacity',
        'filter',
        'resize',
        'cursor',
        'nav-index',
        'nav-up',
        'nav-right',
        'nav-down',
        'nav-left',
        'transition',
        'transition-delay',
        'transition-timing-function',
        'transition-duration',
        'transition-property',
        'transform',
        'transform-origin',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-play-state',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        'animation-fill-mode',
        'pointer-events',
        'unicode-bidi',
        'direction',
        'columns',
        'column-span',
        'column-width',
        'column-count',
        'column-fill',
        'column-gap',
        'column-rule',
        'column-rule-width',
        'column-rule-style',
        'column-rule-color',
        'break-before',
        'break-inside',
        'break-after',
        'page-break-before',
        'page-break-inside',
        'page-break-after',
        'orphans',
        'widows',
        'zoom',
        'max-zoom',
        'min-zoom',
        'user-zoom',
        'orientation',
        'user-select',
        'fill',
        'stroke',
      ],
      {
        unspecified: 'bottom',
      },
    ],
  },
};
